apiVersion: v1
kind: Pod
metadata:
  name: s3-download
spec:
  containers:
  - name: s3-downloader
    image: amazonlinux:2
    command: ["/bin/sh", "-c"]
    args:
      - |
        yum install wget
        yum install unzip -y
     

        # Download file from S3
        wget https://woedpress-snapshot.s3.eu-north-1.amazonaws.com/wp.zip
        # Extract the tar.gz file
        unzip -o wp.zip

        mv wordpress_files/* .

        # Keep the container running to access it if needed
        while true; do sleep 3600; done
    volumeMounts:
    - name: node-storage
      mountPath: /mnt
  volumes:
  - name: node-storage
    hostPath:
      path: /mnt
