apiVersion: v1
kind: Pod
metadata:
  name: s3-download
spec:
  containers:
  - name: s3-downloader
    image: amazonlinux:2
    command: ["/bin/sh", "-c"]
    args:
      - |
        # Install curl and tar
        yum install -y curl tar

        # Download file from S3
        curl -o /mnt/wordpress_files.tar.gz https://woedpress-snapshot.s3.eu-north-1.amazonaws.com/wordpress_files.tar.gz

        # Extract the tar.gz file
        tar -xzvf /mnt/wordpress_files.tar.gz -C /mnt

        # Keep the container running to access it if needed
        while true; do sleep 3600; done
    volumeMounts:
    - name: node-storage
      mountPath: /mnt
  volumes:
  - name: node-storage
    hostPath:
      path: /mnt
