name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read # This is usually required to access your repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::010526256256:role/oidc_role
          audience: sts.amazonaws.com

      #- name: Run Terraform
      #  run: |
      #    cd src
      #    terraform init
      #    terraform apply -auto-approve
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name poly-cluster  # Replace with your cluster name

      - name: Deploy to EKS
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl apply -f kube_manifest/argo_secret_auth.yaml
          kubectl apply -f kube_manifest/argo_config.yaml
