name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: eu-north-1
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          audience: sts.amazonaws.com

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Check kubectl version
        run: kubectl version --client

      - name: Check AWS CLI version
        run: aws --version

      - name: Update cluster authentication mode and kubeconfig
        run: |
          # Update the cluster's authentication mode to API_AND_CONFIG_MAP
          aws eks update-cluster-config \
            --name poly-cluster \
            --resources-vpc-config endpointPublicAccess=true \
            --authentication-mode API_AND_CONFIG_MAP

          # Update kubeconfig to use the correct context
          aws eks update-kubeconfig --name poly-cluster

          # Verify the current context
          kubectl config get-contexts
          kubectl config current-context

      - name: create github access entry
        run: aws eks create-access-entry --cluster-name poly-cluster --principal-arn ${{secrets.OIDC_ROLE}} --username github-actions --kubernetes-groups masters

      - name: Deploy to EKS
        run: |
          kubectl create namespace argocd "
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl apply -f kube_manifest/argo_secret_auth.yaml
          kubectl apply -f kube_manifest/argo_config.yaml

        #- name: Run Terraform
        #  run: |
        #    cd src
        #    terraform init
        #    terraform apply -auto-approve
